server:
  port: 8099

spring:
  datasource:
    url: "jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=quanlikhoahoc;encrypt=true;trustServerCertificate=true"
    username: "sa"
    password: "vuhoangquan2004"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect


